---
jobs:
  build:
    runs-on: my_agent
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml && mkdir artifact && cp target/*.*ar artifact
    - name: Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: artifact
name: Java CI with Maven
on :
  pull_request:
    branches:
    - my_trigger
  push:
    branches:
    - my_trigger
